In [2]:
import pandas as pd
from statsbombpy import sb
from mplsoccer import VerticalPitch,Pitch
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
# find free competitions
comps = sb.competitions()
comps

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093,2025-11-15T23:17:41.827093,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694,None,2026-05-15T15:54:04.598614
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882
...,...,...,...,...,...,...,...,...,...,...,...,...
75,35,75,Europe,UEFA Europa League,male,False,False,1988/1989,2026-04-11T12:48:10.012987,2021-06-13T16:17:31.694,None,2026-04-11T12:48:10.012987
76,53,315,Europe,UEFA Women's Euro,female,False,True,2025,2026-04-27T22:02:42.690507,2026-04-27T22:03:28.087062,2026-04-27T22:03:28.087062,2026-04-27T22:02:42.690507
77,53,106,Europe,UEFA Women's Euro,female,False,True,2022,2026-05-05T03:03:04.199896,2026-05-05T03:05:32.480837,2026-05-05T03:05:32.480837,2026-05-05T03:03:04.199896
78,72,107,International,Women's World Cup,female,False,True,2023,2026-05-03T13:51:31.021141,2026-05-03T13:55:52.303219,2026-05-03T13:55:52.303219,2026-05-03T13:51:31.021141
79,72,30,International,Women's World Cup,female,False,True,2019,2026-05-15T15:31:40.299642,2021-06-13T16:17:31.694,None,2026-05-15T15:31:40.299642

In [ ]:
matches = sb.matches(competition_id=49, season_id=107)
matches

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,...,last_updated_360,match_week,competition_stage,stadium,referee,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version
0,3881583,2023-08-27,00:30:00.000,United States of America - NWSL,2023,Houston Dash,KC Current,1,1,available,...,None,17,Regular Season,Shell Energy Stadium,Shawn Tehini,Sam Laity,Caroline Sjöblom,1.1.0,2,2
1,3881524,2023-05-14,22:00:00.000,United States of America - NWSL,2023,KC Current,San Diego Wave,0,2,available,...,None,7,Regular Season,Children''s Mercy Park,Danielle Chesky,Caroline Sjöblom,Casey Stoney,1.1.0,2,2
2,3881501,2023-04-23,21:00:00.000,United States of America - NWSL,2023,KC Current,Orlando Pride,2,0,available,...,None,4,Regular Season,Children''s Mercy Park,Karen Callado,Caroline Sjöblom,Sebastian Tony Hines,1.1.0,2,2
3,3881512,2023-04-30,22:00:00.000,United States of America - NWSL,2023,KC Current,NJ/NY Gotham FC,2,0,available,...,None,5,Regular Season,Children''s Mercy Park,Adorae Monroy,Caroline Sjöblom,Juan Carlos Amorós,1.1.0,2,2
4,3881540,2023-06-04,00:30:00.000,United States of America - NWSL,2023,KC Current,North Carolina Courage,1,0,available,...,None,10,Regular Season,Children''s Mercy Park,JC Griggs,Caroline Sjöblom,Sean Nahas,1.1.0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,3881487,2023-03-27,01:00:00.000,United States of America - NWSL,2023,Houston Dash,Racing Louisville FC,0,0,available,...,None,1,Regular Season,Shell Energy Stadium,Danielle Chesky,Sam Laity,Kim Björkegren,1.1.0,2,2
133,3881486,2023-03-26,23:00:00.000,United States of America - NWSL,2023,Portland Thorns,Orlando Pride,4,0,available,...,None,1,Regular Season,Providence Park,Eric Tattersall,Mike Norris,Sebastian Tony Hines,1.1.0,2,2
134,3881485,2023-03-26,22:00:00.000,United States of America - NWSL,2023,Washington Spirit,Seattle Reign,1,0,available,...,None,1,Regular Season,Audi Field,Alyssa Nichols,Mark Richard David Parsons,Laura Harvey,1.1.0,2,2
135,3881484,2023-03-26,04:00:00.000,United States of America - NWSL,2023,San Diego Wave,Chicago Red Stars,3,2,available,...,None,1,Regular Season,Snapdragon Stadium,Elton Garcia,Casey Stoney,Christopher Joseph Petrucelli,1.1.0,2,2
136,3881483,2023-03-25,18:00:00.000,United States of America - NWSL,2023,North Carolina Courage,KC Current,1,0,available,...,None,1,Regular Season,WakeMed Soccer Park,Alex Billeter,Sean Nahas,Matt Potter,1.1.0,2,2